use_frameworks!

platform :ios, '10.0'

target 'UnityHelper_Example' do
  pod 'UnityHelper', :path => '../'

  target 'UnityHelper_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
